### ISSUE TITLE
Using em units

### ISSUE THREAD

**Issue by coreyworrell** [philipwalton/responsive-components#3]
One solution for making this work with different font sizes is to divide the widths by the font size of the root element. The way `em` media queries work is they are based off of the browser default, regardless of what `html` element `font-size` is set to via CSS. So one method is to get the `html` element's font-size as the default for this division, and then allow the user to override that if they want to.

https://github.com/philipwalton/responsive-components/blob/master/app/templates/_resize-observer.html#L31

```
if (entry.contentRect.width >= minWidth) {
```

becomes

```js
// these could be overridable options
const rootFontSize = parseInt(getComputedStyle(document.documentElement).fontSize)
const baseFontSize = 16
// 16 is because that is default in most/all browsers, and most likely the setting when developers get their breakpoint values, but of course it can be overridden if needed
...

if (relativeSize(entry.contentRect.width) >= minWidth) {

...

function relativeSize(value, base) {
    return value * (baseFontSize / rootFontsize)
}
```

Hopefully that makes sense.. Running the code may make more sense.

**Comment by philipwalton** [comment]
> The way `em` media queries work is they are based off of the browser default, regardless of what `html` element `font-size` is set to via CSS.

That's true, but that's because they're based on the viewport. For container queries I'd expect ems to be relative to the container element's font size.

> `const rootFontSize = parseInt(getComputedStyle(document.documentElement).fontSize)`

Using `getComputedStyle()` isn't really an option because it'd force a style re-calc every time it ran. Since ResizeObserver callbacks can run very frequently, I'd want to avoid any code that requires a layout or style re-calc.

**Comment by coreyworrell** [comment]
Well, you could just call it once at the initial page load to get the value, and then leave it up to the user of the library to call a "refresh" method or something that would recalculate those font sizes if necessary. And yes you could base the `em` size off of the container as well, doesn't really matter as long as you end up with a "relative" unit to work with that will always trigger the right layout at the right time (ie: 300px wide at 16px font size == 450px at 24px font size)

**Comment by philipwalton** [comment]
I think this issue is best left to individual developers to choose how they want to implement it. There's no good, performant way to do this in a simple code snippet that handles all cases where a container element's styles could change.

It's also not just about ems. There are lots of other relative units you'd have to handle as well (another reason I think it's best to just let individual sites implement their own strategy).
